config/routes.rb
Rails.application.routes.draw do
  root "top#index"
  get "about" => "top#about", as: "about"
  get "bad_request" => "top#bad_request"
  get "internal_server_error" => "top#internal_server_error"
  get "lesson/:action(/:name)" => "lesson"

  resources :members, only: [:index, :show] do
    collection { get "search" }
    resources :entries, only: [:index]
  end
  resources :articles, only: [:index, :show]
  resources :entries do
    member { patch :like, :unlike }
    collection { get :voted }
  end
  resource :session, only: [:create, :destroy]
  resource :account

  namespace :admin do
    root to: "top#index"
    resources :members do
      collection { get "search" }
    end
    resources :articles
  end

  match "*anything" => "top#not_found", via: [:get, :post, :patch, :delete]
end

app/views/shared/_errors.html.erb
<% if obj.errors.present? %>
<div id="errors">
<h3>エラーがあります。</h3>
<ul>
  <% obj.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
  <% end %>
</ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%= link_to "このサイトについて", about_path %> |
Copyright (C) <%= link_to "Oiax Inc.", "http://www.oiax.co.jp/" %>
2007-2015

app/views/shared/_header.html.erb
<%= image_tag("logo.gif", size: "272x48", alt: "Morning Glory") %>

<% if current_member %>
<p class="member">
<%= link_to current_member.name + "さん", :account %> |
<%= link_to "ログアウト", :session,
      method: :delete, data: { confirm: "ログアウトしますか？" } %>
</p>
<% end %>

<% if controller.kind_of?(Admin::Base) %>
<div class="menubar" id="admin_menubar">
<%= menu_link_to "管理TOP", :admin_root %>
&nbsp;|&nbsp; <%= menu_link_to "会員管理", :admin_members %>
&nbsp;|&nbsp; <%= menu_link_to "記事管理", :admin_articles %>
&nbsp;|&nbsp; <%= menu_link_to "TOP", :root %>
</div>
<% else %>
<div class="menubar">
<%= menu_link_to "TOP", root_path %>
&nbsp;|&nbsp; <%= menu_link_to "ニュース", :articles %>
&nbsp;|&nbsp; <%= menu_link_to "ブログ", :entries %>
<% if current_member %>
&nbsp;|&nbsp; <%= menu_link_to "会員名簿", :members %>
<% if current_member.administrator? %>
&nbsp;|&nbsp; <%= menu_link_to "管理ページ", :admin_root %>
<% end %>
<% end %>
</div>
<% end %>

app/views/shared/_login_form.html.erb
<h2>ログイン</h2>
<% if flash.alert %><p class="alert"><%= flash.alert %></p><% end %>
<%= form_tag :session do %>
<table id="login_form">
  <tr>
    <td style="text-align: right">ユーザー名：</td>
    <td><%= text_field_tag "name", "", style: "width: 120px" %></td>
  </tr>
  <tr>
    <td style="text-align: right">パスワード：</td>
    <td><%= password_field_tag "password", "", style: "width: 120px" %></td>
  </tr>
  <tr>
    <td colspan="2" style="text-align: center">
    <%= submit_tag "ログイン" %></td>
  </tr>
</table>
<% end %>

app/views/shared/_sidebar.html.erb
<%= render "shared/login_form" unless current_member %>

<h2>最新ニュース</h2>
<ul>
  <% Article.sidebar_articles(current_member, 5).each do |article| %>
  <li><%= link_to article.title, article %></li>
  <% end %>
</ul>

<h2>会員のブログ</h2>
<ul>
  <% Entry.sidebar_entries(current_member, 5).each do |entry| %>
  <li>
    <%= link_to entry.title, entry %>
    by <%= link_to entry.author.name, [entry.author, :entries] %>
  </li>
  <% end %>
</ul>